In [1]:
import pandas as pd

In [2]:
import os
print(os.getcwd())

c:\Users\DELL E5540\Desktop\LaptopIQ\Data_cleaning

In [3]:
import os

print(os.listdir())

['cleaned_laptop_data_for_rag.csv', 'cleaning_file_for_rag.ipynb']

In [4]:
df = pd.read_csv(r"C:\Users\DELL E5540\Desktop\LaptopIQ\Data\laptop_price - dataset.csv")

In [5]:
df.head(5)

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

Company                0
Product                0
TypeName               0
Inches                 0
ScreenResolution       0
CPU_Company            0
CPU_Type               0
CPU_Frequency (GHz)    0
RAM (GB)               0
Memory                 0
GPU_Company            0
GPU_Type               0
OpSys                  0
Weight (kg)            0
Price (Euro)           0
dtype: int64

In [8]:
EUR_TO_USD = 1.10
df['Price (USD)'] = df['Price (Euro)'] * EUR_TO_USD

In [9]:
df.head(3)

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro),Price (USD)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69,1473.659
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94,988.834
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00,632.500

In [10]:
df = df.drop(["CPU_Company", "GPU_Company", "Price (Euro)","ScreenResolution","CPU_Frequency (GHz)","Inches","TypeName","GPU_Type"], axis=1 )

In [11]:
df.head()

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,Apple,MacBook Pro,Core i5,8,128GB SSD,macOS,1.37,1473.659
1,Apple,Macbook Air,Core i5,8,128GB Flash Storage,macOS,1.34,988.834
2,HP,250 G6,Core i5 7200U,8,256GB SSD,No OS,1.86,632.500
3,Apple,MacBook Pro,Core i7,16,512GB SSD,macOS,1.83,2791.195
4,Apple,MacBook Pro,Core i5,8,256GB SSD,macOS,1.37,1983.960

In [12]:
print (df.columns)

Index(['Company', 'Product', 'CPU_Type', 'RAM (GB)', 'Memory', 'OpSys',
       'Weight (kg)', 'Price (USD)'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      1275 non-null   str
 1   Product      1275 non-null   str
 2   CPU_Type     1275 non-null   str
 3   RAM (GB)     1275 non-null   int64
 4   Memory       1275 non-null   str
 5   OpSys        1275 non-null   str
 6   Weight (kg)  1275 non-null   float64
 7   Price (USD)  1275 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 147.1 KB

In [14]:
print(len(df))

1275

In [15]:
print(df.columns)

Index(['Company', 'Product', 'CPU_Type', 'RAM (GB)', 'Memory', 'OpSys',
       'Weight (kg)', 'Price (USD)'],
      dtype='str')

In [16]:
text_cols = [
    "Company",
    "Product",
    "CPU_Type",
    "Memory",
    "OpSys"
]

for col in text_cols:
    df[col] = df[col].str.strip()

In [17]:
df.head(5)

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,Apple,MacBook Pro,Core i5,8,128GB SSD,macOS,1.37,1473.659
1,Apple,Macbook Air,Core i5,8,128GB Flash Storage,macOS,1.34,988.834
2,HP,250 G6,Core i5 7200U,8,256GB SSD,No OS,1.86,632.500
3,Apple,MacBook Pro,Core i7,16,512GB SSD,macOS,1.83,2791.195
4,Apple,MacBook Pro,Core i5,8,256GB SSD,macOS,1.37,1983.960

In [18]:
def clean_weight(weight):
    if isinstance(weight, str):
        weight = weight.replace('kg', '').strip()
    try:
        return float(weight)
    except:
        return None

In [19]:
df.head()

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,Apple,MacBook Pro,Core i5,8,128GB SSD,macOS,1.37,1473.659
1,Apple,Macbook Air,Core i5,8,128GB Flash Storage,macOS,1.34,988.834
2,HP,250 G6,Core i5 7200U,8,256GB SSD,No OS,1.86,632.500
3,Apple,MacBook Pro,Core i7,16,512GB SSD,macOS,1.83,2791.195
4,Apple,MacBook Pro,Core i5,8,256GB SSD,macOS,1.37,1983.960

In [20]:
def clean_os(os_name):
    if pd.isna(os_name): return "Unknown"
    os_name = os_name.strip()
    # Standardizing names for better RAG retrieval
    if 'Mac' in os_name or 'macOS' in os_name:
        return 'macOS'
    elif 'Windows' in os_name:
        return 'Windows' # 'Windows 10' ko 'Windows' bhi saktay ho agar generic chahiye
    elif 'Linux' in os_name or 'Ubuntu' in os_name:
        return 'Linux'
    elif 'Android' in os_name:
        return 'Android'
    elif 'No OS' in os_name:
        return 'No OS'
    else:
        return os_name

In [21]:
df.head()

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,Apple,MacBook Pro,Core i5,8,128GB SSD,macOS,1.37,1473.659
1,Apple,Macbook Air,Core i5,8,128GB Flash Storage,macOS,1.34,988.834
2,HP,250 G6,Core i5 7200U,8,256GB SSD,No OS,1.86,632.500
3,Apple,MacBook Pro,Core i7,16,512GB SSD,macOS,1.83,2791.195
4,Apple,MacBook Pro,Core i5,8,256GB SSD,macOS,1.37,1983.960

In [22]:
def clean_memory(memory):
    if pd.isna(memory): return ""
    return memory.strip().replace("  ", " ")

In [23]:
df.head(5)

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,Apple,MacBook Pro,Core i5,8,128GB SSD,macOS,1.37,1473.659
1,Apple,Macbook Air,Core i5,8,128GB Flash Storage,macOS,1.34,988.834
2,HP,250 G6,Core i5 7200U,8,256GB SSD,No OS,1.86,632.500
3,Apple,MacBook Pro,Core i7,16,512GB SSD,macOS,1.83,2791.195
4,Apple,MacBook Pro,Core i5,8,256GB SSD,macOS,1.37,1983.960

In [24]:
def create_document_text(row):
    """
    RAG ke liye ek sentence generate karna taake search easy ho.
    """
    return (f"Company: {row['Company']}, "
            f"Product: {row['Product']}, "
            f"CPU:  {row['CPU_Type']} , "
            f"RAM: {row['RAM (GB)']} GB, "
            f"Memory: {row['Memory']}, "
            f"OS: {row['OpSys']}, "
            f"Weight: {row['Weight (kg)']} kg, "
            f"Price: {row['Price (USD)']} USD, ")

In [25]:
df.columns = df.columns.str.strip()

df['Weight (kg)'] = df['Weight (kg)'].apply(clean_weight)
df['OpSys'] = df['OpSys'].apply(clean_os)
df['Memory'] = df['Memory'].apply(clean_memory)

In [26]:
df['Product'] = df['Product'].str.split('(').str[0].str.strip()

In [27]:
df = df.sample(n=200).reset_index(drop=True)

In [28]:
print(len(df))

200

In [29]:
df

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,Lenovo,Thinkpad 13,Core i7 7500U,8,256GB SSD,Windows,1.40,1111.000
1,Lenovo,IdeaPad 320-15ISK,Core i3 6006U,4,128GB SSD,No OS,2.20,405.900
2,Toshiba,Satellite Pro,Core i5 7200U,8,128GB SSD,Windows,2.00,872.300
3,Dell,Inspiron 3567,Core i5 7200U,4,256GB SSD,Windows,2.30,702.900
4,HP,ProBook 440,Core i7 7500U,8,256GB SSD,Windows,1.64,1303.973
...,...,...,...,...,...,...,...,...
195,HP,ProBook 430,Core i5 8250U,8,512GB SSD,Windows,1.49,1054.900
196,Acer,SP714-51,Core i7 7Y75,8,256GB SSD,Windows,1.20,1263.900
197,Asus,X542UQ-GO005,Core i5 7200U,8,1TB HDD,Linux,2.30,575.289
198,Asus,ZenBook UX310UA-WB71,Core i7 6500U,8,256GB SSD,Windows,1.45,1408.000
199,Dell,XPS 13,Core i5 8250U,8,256GB SSD,Windows,1.23,2055.900

In [30]:
df.to_csv('cleaned_laptop_data_for_rag.csv', index=False)

In [213]:
df.head(5)

,Company,Product,CPU_Type,RAM (GB),Memory,OpSys,Weight (kg),Price (USD)
0,MSI,GP62M 7RDX,Core i7 7700HQ,8,128GB SSD + 1TB HDD,Windows,2.40,1257.08
1,Dell,Vostro 3568,Core i5 7200U,4,1TB HDD,Windows,2.18,722.70
2,Microsoft,Surface Laptop,Core i7 7660U,8,256GB SSD,Windows,1.25,1978.90
3,Asus,Vivobook E200HA,Atom x5-Z8350,2,32GB Flash Storage,Windows,0.98,211.09
4,HP,Omen 17-an006nv,Core i7 7700HQ,12,1TB HDD,Windows,3.78,1868.90